edition = "2021"
max_width = 80
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# unstable (requires nightly rustfmt)
unstable_features = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
comment_width = 80
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
error_on_line_overflow = true
brace_style = "SameLineWhere"
